//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Global_Button_Accept {
            get {
                return ResourceManager.GetString("Global_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Global_Button_Back {
            get {
                return ResourceManager.GetString("Global_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Global_Button_Cancel {
            get {
                return ResourceManager.GetString("Global_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom.
        /// </summary>
        public static string Global_Button_Custom {
            get {
                return ResourceManager.GetString("Global_Button_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string Global_Button_Guest {
            get {
                return ResourceManager.GetString("Global_Button_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string Global_Button_Join {
            get {
                return ResourceManager.GetString("Global_Button_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string Global_Button_LogIn {
            get {
                return ResourceManager.GetString("Global_Button_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Ready.
        /// </summary>
        public static string Global_Button_NotReady {
            get {
                return ResourceManager.GetString("Global_Button_NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Global_Button_Play {
            get {
                return ResourceManager.GetString("Global_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string Global_Button_Ready {
            get {
                return ResourceManager.GetString("Global_Button_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Global_Button_Send {
            get {
                return ResourceManager.GetString("Global_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Global_Button_Settings {
            get {
                return ResourceManager.GetString("Global_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set up Profile.
        /// </summary>
        public static string Global_Button_SetupProfile {
            get {
                return ResourceManager.GetString("Global_Button_SetupProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string Global_Button_SignIn {
            get {
                return ResourceManager.GetString("Global_Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify.
        /// </summary>
        public static string Global_Button_Verify {
            get {
                return ResourceManager.GetString("Global_Button_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your verification code has expired. Please request a new one.
        /// </summary>
        public static string Global_Error_CodeExpired {
            get {
                return ResourceManager.GetString("Global_Error_CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification failed. Please check the code and try again.
        /// </summary>
        public static string Global_Error_CodeInvalid {
            get {
                return ResourceManager.GetString("Global_Error_CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email address is already in use.
        /// </summary>
        public static string Global_Error_EmailInUse {
            get {
                return ResourceManager.GetString("Global_Error_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to send verification email.
        /// </summary>
        public static string Global_Error_EmailSendFailed {
            get {
                return ResourceManager.GetString("Global_Error_EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests are not allowed to create lobbies. Please register or log in to access this feature.
        /// </summary>
        public static string Global_Error_GuestsNotAllowed {
            get {
                return ResourceManager.GetString("Global_Error_GuestsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image format is not valid.
        /// </summary>
        public static string Global_Error_ImageInvalid {
            get {
                return ResourceManager.GetString("Global_Error_ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email or password.
        /// </summary>
        public static string Global_Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Global_Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your session is invalid or has expired. Please log in again.
        /// </summary>
        public static string Global_Error_InvalidToken {
            get {
                return ResourceManager.GetString("Global_Error_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a username is not valid or is already taken. Please try another.
        /// </summary>
        public static string Global_Error_InvalidUsername {
            get {
                return ResourceManager.GetString("Global_Error_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not have a valid format.
        /// </summary>
        public static string Global_Error_PasswordInvalid {
            get {
                return ResourceManager.GetString("Global_Error_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registration request was found for this email.
        /// </summary>
        public static string Global_Error_RegistrationNotFound {
            get {
                return ResourceManager.GetString("Global_Error_RegistrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That username is already in use. Please choose another.
        /// </summary>
        public static string Global_Error_UsernameInUse {
            get {
                return ResourceManager.GetString("Global_Error_UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.
        /// </summary>
        public static string Global_Error_UserNotFound {
            get {
                return ResourceManager.GetString("Global_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cards.
        /// </summary>
        public static string Global_Label_Cards {
            get {
                return ResourceManager.GetString("Global_Label_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty;.
        /// </summary>
        public static string Global_Label_Difficulty {
            get {
                return ResourceManager.GetString("Global_Label_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Global_Label_Email {
            get {
                return ResourceManager.GetString("Global_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter 6 digit code:.
        /// </summary>
        public static string Global_Label_EnterCode {
            get {
                return ResourceManager.GetString("Global_Label_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an username:.
        /// </summary>
        public static string Global_Label_EnterUsername {
            get {
                return ResourceManager.GetString("Global_Label_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of cards.
        /// </summary>
        public static string Global_Label_NumberOfCards {
            get {
                return ResourceManager.GetString("Global_Label_NumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Global_Label_Password {
            get {
                return ResourceManager.GetString("Global_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        public static string Global_Label_Score {
            get {
                return ResourceManager.GetString("Global_Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seconds.
        /// </summary>
        public static string Global_Label_Seconds {
            get {
                return ResourceManager.GetString("Global_Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer:.
        /// </summary>
        public static string Global_Label_Time {
            get {
                return ResourceManager.GetString("Global_Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer Limit:.
        /// </summary>
        public static string Global_Label_TimerLimit {
            get {
                return ResourceManager.GetString("Global_Label_TimerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome, {0}!.
        /// </summary>
        public static string Global_Message_Welcome {
            get {
                return ResourceManager.GetString("Global_Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Guest).
        /// </summary>
        public static string Global_Player_GuestSuffix {
            get {
                return ResourceManager.GetString("Global_Player_GuestSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication error. The network may be unstable.
        /// </summary>
        public static string Global_ServiceError_NetworkDown {
            get {
                return ResourceManager.GetString("Global_ServiceError_NetworkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to connect to the server. Please check your connection.
        /// </summary>
        public static string Global_ServiceError_Offline {
            get {
                return ResourceManager.GetString("Global_ServiceError_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error has occurred.
        /// </summary>
        public static string Global_ServiceError_Unknown {
            get {
                return ResourceManager.GetString("Global_ServiceError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application Error.
        /// </summary>
        public static string Global_Title_AppError {
            get {
                return ResourceManager.GetString("Global_Title_AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Global_Title_Chat {
            get {
                return ResourceManager.GetString("Global_Title_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Settings.
        /// </summary>
        public static string Global_Title_CustomDifficulty {
            get {
                return ResourceManager.GetString("Global_Title_CustomDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Global_Title_Error {
            get {
                return ResourceManager.GetString("Global_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Global_Title_Information {
            get {
                return ResourceManager.GetString("Global_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string Global_Title_Lobby {
            get {
                return ResourceManager.GetString("Global_Title_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logged in as a successful guest.
        /// </summary>
        public static string Global_Title_LoginAsGuestSuccess {
            get {
                return ResourceManager.GetString("Global_Title_LoginAsGuestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login Failed.
        /// </summary>
        public static string Global_Title_LoginFailed {
            get {
                return ResourceManager.GetString("Global_Title_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login Successful.
        /// </summary>
        public static string Global_Title_LoginSuccess {
            get {
                return ResourceManager.GetString("Global_Title_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplayer.
        /// </summary>
        public static string Global_Title_Multiplayer {
            get {
                return ResourceManager.GetString("Global_Title_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network Error .
        /// </summary>
        public static string Global_Title_NetworkError {
            get {
                return ResourceManager.GetString("Global_Title_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Function not available.
        /// </summary>
        public static string Global_Title_NotAvailableFunction {
            get {
                return ResourceManager.GetString("Global_Title_NotAvailableFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string Global_Title_Players {
            get {
                return ResourceManager.GetString("Global_Title_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server Offline.
        /// </summary>
        public static string Global_Title_ServerOffline {
            get {
                return ResourceManager.GetString("Global_Title_ServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Singleplayer.
        /// </summary>
        public static string Global_Title_Singleplayer {
            get {
                return ResourceManager.GetString("Global_Title_Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string Global_Title_Success {
            get {
                return ResourceManager.GetString("Global_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Global_Title_Warning {
            get {
                return ResourceManager.GetString("Global_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code cannot be empty.
        /// </summary>
        public static string Global_ValidationCode_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code must not exceed 6 characters.
        /// </summary>
        public static string Global_ValidationCode_LengthInvalid {
            get {
                return ResourceManager.GetString("Global_ValidationCode_LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code should only contain numbers.
        /// </summary>
        public static string Global_ValidationCode_NotNumeric {
            get {
                return ResourceManager.GetString("Global_ValidationCode_NotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email cannot be empty.
        /// </summary>
        public static string Global_ValidationEmail_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationEmail_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email format is invalid. Please enter a valid address.
        /// </summary>
        public static string Global_ValidationEmail_InvalidFormat {
            get {
                return ResourceManager.GetString("Global_ValidationEmail_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password cannot be empty.
        /// </summary>
        public static string Global_ValidationPassword_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must be between 8 and 20 characters long.
        /// </summary>
        public static string Global_ValidationPassword_LengthInvalid {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one number.
        /// </summary>
        public static string Global_ValidationPassword_MissingDigit {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one lowercase letter.
        /// </summary>
        public static string Global_ValidationPassword_MissingLower {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password must contain at least one uppercase letter.
        /// </summary>
        public static string Global_ValidationPassword_MissingUpper {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username cannot be empty.
        /// </summary>
        public static string Global_ValidationUsername_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username must not contain spaces; use - or _ instead.
        /// </summary>
        public static string Global_ValidationUsername_InvalidChars {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username must be 30 characters or less.
        /// </summary>
        public static string Global_ValidationUsername_TooLong {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send invitation.
        /// </summary>
        public static string HostLobby_Button_SendInvitation {
            get {
                return ResourceManager.GetString("HostLobby_Button_SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create lobby.
        /// </summary>
        public static string HostLobby_Error_CreateFailed {
            get {
                return ResourceManager.GetString("HostLobby_Error_CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a valid email address.
        /// </summary>
        public static string HostLobby_Error_EmailInvalid {
            get {
                return ResourceManager.GetString("HostLobby_Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to send invitation. Please try again later.
        /// </summary>
        public static string HostLobby_Error_InviteFailed {
            get {
                return ResourceManager.GetString("HostLobby_Error_InviteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Available.
        /// </summary>
        public static string HostLobby_Label_Available {
            get {
                return ResourceManager.GetString("HostLobby_Label_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your friend&apos;s email:.
        /// </summary>
        public static string HostLobby_Label_EnterFriendEmail {
            get {
                return ResourceManager.GetString("HostLobby_Label_EnterFriendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code:.
        /// </summary>
        public static string HostLobby_Label_GameCode {
            get {
                return ResourceManager.GetString("HostLobby_Label_GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time per Turn:.
        /// </summary>
        public static string HostLobby_Label_TimePerTurn {
            get {
                return ResourceManager.GetString("HostLobby_Label_TimePerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent successfully to {0}.
        /// </summary>
        public static string HostLobby_Message_InviteSent {
            get {
                return ResourceManager.GetString("HostLobby_Message_InviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game settings.
        /// </summary>
        public static string HostLobby_Title_GameSettings {
            get {
                return ResourceManager.GetString("HostLobby_Title_GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite friends.
        /// </summary>
        public static string HostLobby_Title_InviteFriends {
            get {
                return ResourceManager.GetString("HostLobby_Title_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guests are not allowed to send chat messages.
        /// </summary>
        public static string Lobby_Error_GuestChat {
            get {
                return ResourceManager.GetString("Lobby_Error_GuestChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to join lobby. Invalid code or lobby is full.
        /// </summary>
        public static string Lobby_Error_JoinFailed {
            get {
                return ResourceManager.GetString("Lobby_Error_JoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to send chat message.
        /// </summary>
        public static string Lobby_Error_SendChatFailed {
            get {
                return ResourceManager.GetString("Lobby_Error_SendChatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby successfully created!.
        /// </summary>
        public static string Lobby_Message_CreateSuccess {
            get {
                return ResourceManager.GetString("Lobby_Message_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has joined the lobby.
        /// </summary>
        public static string Lobby_Notification_PlayerJoined {
            get {
                return ResourceManager.GetString("Lobby_Notification_PlayerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has left the lobby.
        /// </summary>
        public static string Lobby_Notification_PlayerLeft {
            get {
                return ResourceManager.GetString("Lobby_Notification_PlayerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [System].
        /// </summary>
        public static string Lobby_Notification_System {
            get {
                return ResourceManager.GetString("Lobby_Notification_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit game.
        /// </summary>
        public static string MainMenu_Button_ExitGame {
            get {
                return ResourceManager.GetString("MainMenu_Button_ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gallery.
        /// </summary>
        public static string MainMenu_Button_Gallery {
            get {
                return ResourceManager.GetString("MainMenu_Button_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create lobby.
        /// </summary>
        public static string MultiplayerMenu_Button_CreateLobby {
            get {
                return ResourceManager.GetString("MultiplayerMenu_Button_CreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration failed. The email may already be in use.
        /// </summary>
        public static string RegisterAccount_Message_Failed {
            get {
                return ResourceManager.GetString("RegisterAccount_Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration successful! A verification code has been sent to your email.
        /// </summary>
        public static string RegisterAccount_Message_Success {
            get {
                return ResourceManager.GetString("RegisterAccount_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy.
        /// </summary>
        public static string SelectDifficulty_Button_Easy {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard.
        /// </summary>
        public static string SelectDifficulty_Button_Hard {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string SelectDifficulty_Button_Normal {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio.
        /// </summary>
        public static string Settings_Label_Audio {
            get {
                return ResourceManager.GetString("Settings_Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Settings.
        /// </summary>
        public static string Settings_Label_General {
            get {
                return ResourceManager.GetString("Settings_Label_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Settings_Label_Language {
            get {
                return ResourceManager.GetString("Settings_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        public static string Settings_Label_Music {
            get {
                return ResourceManager.GetString("Settings_Label_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SFX Volume.
        /// </summary>
        public static string Settings_Label_SFX {
            get {
                return ResourceManager.GetString("Settings_Label_SFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English (US).
        /// </summary>
        public static string Settings_Language_EnUS {
            get {
                return ResourceManager.GetString("Settings_Language_EnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish (MX).
        /// </summary>
        public static string Settings_Language_EsMX {
            get {
                return ResourceManager.GetString("Settings_Language_EsMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Files|*.jpg;*.jpeg;*.png;*.bmp.
        /// </summary>
        public static string SetupProfile_Dialog_Filter {
            get {
                return ResourceManager.GetString("SetupProfile_Dialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Profile Image.
        /// </summary>
        public static string SetupProfile_Dialog_Title {
            get {
                return ResourceManager.GetString("SetupProfile_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load image: {0}.
        /// </summary>
        public static string SetupProfile_Error_ImageLoad {
            get {
                return ResourceManager.GetString("SetupProfile_Error_ImageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an avatar:.
        /// </summary>
        public static string SetupProfile_Label_SelectAvatar {
            get {
                return ResourceManager.GetString("SetupProfile_Label_SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile setup complete! Welcome.
        /// </summary>
        public static string SetupProfile_Message_Success {
            get {
                return ResourceManager.GetString("SetupProfile_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try faster next time.
        /// </summary>
        public static string Singleplayer_Label_TimeOver {
            get {
                return ResourceManager.GetString("Singleplayer_Label_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time&apos;s Up! :(.
        /// </summary>
        public static string Singleplayer_Title_TimeOver {
            get {
                return ResourceManager.GetString("Singleplayer_Title_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Pairs Found! :D.
        /// </summary>
        public static string Singleplayer_Title_Won {
            get {
                return ResourceManager.GetString("Singleplayer_Title_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memory Game.
        /// </summary>
        public static string TitleScreen_Label_Memorama {
            get {
                return ResourceManager.GetString("TitleScreen_Label_Memorama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code forwarded.
        /// </summary>
        public static string Verify_Message_CodeResent {
            get {
                return ResourceManager.GetString("Verify_Message_CodeResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send again?.
        /// </summary>
        public static string VerifyCode_Button_SentAgain {
            get {
                return ResourceManager.GetString("VerifyCode_Button_SentAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A verification email was sent to:.
        /// </summary>
        public static string VerifyCode_Label_SentTo {
            get {
                return ResourceManager.GetString("VerifyCode_Label_SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been successfully verified!.
        /// </summary>
        public static string VerifyCode_Message_Success {
            get {
                return ResourceManager.GetString("VerifyCode_Message_Success", resourceCulture);
            }
        }
    }
}
