//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string EditProfile_Button_ChangeAvatar {
            get {
                return ResourceManager.GetString("EditProfile_Button_ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string EditProfile_Button_UpdatePassword {
            get {
                return ResourceManager.GetString("EditProfile_Button_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Username.
        /// </summary>
        public static string EditProfile_Button_UpdateUsername {
            get {
                return ResourceManager.GetString("EditProfile_Button_UpdateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Password:.
        /// </summary>
        public static string EditProfile_Label_ActualPassword {
            get {
                return ResourceManager.GetString("EditProfile_Label_ActualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Avatar has been Updated.
        /// </summary>
        public static string EditProfile_Label_AvatarUpdated {
            get {
                return ResourceManager.GetString("EditProfile_Label_AvatarUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile_Label_EditProfile {
            get {
                return ResourceManager.GetString("EditProfile_Label_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Password Fields to Update.
        /// </summary>
        public static string EditProfile_Label_ErrorPasswordFields {
            get {
                return ResourceManager.GetString("EditProfile_Label_ErrorPasswordFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update password. Check your current password.
        /// </summary>
        public static string EditProfile_Label_ErrorPasswordUpdate {
            get {
                return ResourceManager.GetString("EditProfile_Label_ErrorPasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New username is the same as the current one.
        /// </summary>
        public static string EditProfile_Label_ErrorSameUsername {
            get {
                return ResourceManager.GetString("EditProfile_Label_ErrorSameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        public static string EditProfile_Label_ErrorUsernameEmpty {
            get {
                return ResourceManager.GetString("EditProfile_Label_ErrorUsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string EditProfile_Label_NewPassword {
            get {
                return ResourceManager.GetString("EditProfile_Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username:.
        /// </summary>
        public static string EditProfile_Label_NewUsername {
            get {
                return ResourceManager.GetString("EditProfile_Label_NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated.
        /// </summary>
        public static string EditProfile_Label_PasswordUpdated {
            get {
                return ResourceManager.GetString("EditProfile_Label_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated information :D.
        /// </summary>
        public static string EditProfile_Label_SuccesUpdateInfo {
            get {
                return ResourceManager.GetString("EditProfile_Label_SuccesUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username updated successfully. For security reasons, you must log in again.
        /// </summary>
        public static string EditProfile_Label_SuccesUpdateUsername {
            get {
                return ResourceManager.GetString("EditProfile_Label_SuccesUpdateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Personal Information.
        /// </summary>
        public static string EditProfile_Label_UpdatePersonalnfo {
            get {
                return ResourceManager.GetString("EditProfile_Label_UpdatePersonalnfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string Friends_Button_SendRequest {
            get {
                return ResourceManager.GetString("Friends_Button_SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Remove Friend :( Please try Again.
        /// </summary>
        public static string Friends_Error_RemoveFriend {
            get {
                return ResourceManager.GetString("Friends_Error_RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be sent. Please try again.
        /// </summary>
        public static string Friends_Error_SendRequest {
            get {
                return ResourceManager.GetString("Friends_Error_SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string Friends_Label_AddFriend {
            get {
                return ResourceManager.GetString("Friends_Label_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username of your friend:.
        /// </summary>
        public static string Friends_Label_EnterUsername {
            get {
                return ResourceManager.GetString("Friends_Label_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends_Label_Friends {
            get {
                return ResourceManager.GetString("Friends_Label_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Friends.
        /// </summary>
        public static string Friends_Label_MyFriends {
            get {
                return ResourceManager.GetString("Friends_Label_MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string Friends_Label_PendingRequests {
            get {
                return ResourceManager.GetString("Friends_Label_PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        public static string Friends_Label_Requests {
            get {
                return ResourceManager.GetString("Friends_Label_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request Sent to {0}.
        /// </summary>
        public static string Friends_Label_SuccessRequest {
            get {
                return ResourceManager.GetString("Friends_Label_SuccessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to want to remove {0}?.
        /// </summary>
        public static string Friends_Message_RemoveFriend {
            get {
                return ResourceManager.GetString("Friends_Message_RemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wants to be your friend.
        /// </summary>
        public static string FriendsMenu_Label_PendingRequests {
            get {
                return ResourceManager.GetString("FriendsMenu_Label_PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Global_Button_Accept {
            get {
                return ResourceManager.GetString("Global_Button_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Global_Button_Back {
            get {
                return ResourceManager.GetString("Global_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Global_Button_Cancel {
            get {
                return ResourceManager.GetString("Global_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Global_Button_Close {
            get {
                return ResourceManager.GetString("Global_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Session.
        /// </summary>
        public static string Global_Button_CloseSession {
            get {
                return ResourceManager.GetString("Global_Button_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Global_Button_Custom {
            get {
                return ResourceManager.GetString("Global_Button_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        public static string Global_Button_ExitGame {
            get {
                return ResourceManager.GetString("Global_Button_ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Global_Button_Guest {
            get {
                return ResourceManager.GetString("Global_Button_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Global_Button_Join {
            get {
                return ResourceManager.GetString("Global_Button_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Global_Button_LogIn {
            get {
                return ResourceManager.GetString("Global_Button_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready.
        /// </summary>
        public static string Global_Button_NotReady {
            get {
                return ResourceManager.GetString("Global_Button_NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Global_Button_Play {
            get {
                return ResourceManager.GetString("Global_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Global_Button_Ready {
            get {
                return ResourceManager.GetString("Global_Button_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Global_Button_Reject {
            get {
                return ResourceManager.GetString("Global_Button_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Global_Button_Remove {
            get {
                return ResourceManager.GetString("Global_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Global_Button_Report {
            get {
                return ResourceManager.GetString("Global_Button_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Global_Button_Send {
            get {
                return ResourceManager.GetString("Global_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Global_Button_Settings {
            get {
                return ResourceManager.GetString("Global_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up Profile.
        /// </summary>
        public static string Global_Button_SetupProfile {
            get {
                return ResourceManager.GetString("Global_Button_SetupProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Global_Button_SignIn {
            get {
                return ResourceManager.GetString("Global_Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Global_Button_Update {
            get {
                return ResourceManager.GetString("Global_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Global_Button_Verify {
            get {
                return ResourceManager.GetString("Global_Button_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. You do not have permission to perform this action..
        /// </summary>
        public static string Global_Error_AccessDenied {
            get {
                return ResourceManager.GetString("Global_Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification code has expired. Please request a new one.
        /// </summary>
        public static string Global_Error_CodeExpired {
            get {
                return ResourceManager.GetString("Global_Error_CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed. Please check the code and try again.
        /// </summary>
        public static string Global_Error_CodeInvalid {
            get {
                return ResourceManager.GetString("Global_Error_CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use.
        /// </summary>
        public static string Global_Error_EmailInUse {
            get {
                return ResourceManager.GetString("Global_Error_EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send verification email.
        /// </summary>
        public static string Global_Error_EmailSendFailed {
            get {
                return ResourceManager.GetString("Global_Error_EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error occurred. The application must close..
        /// </summary>
        public static string Global_Error_FatalCrash {
            get {
                return ResourceManager.GetString("Global_Error_FatalCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests are not allowed to create lobbies. Please register or log in to access this feature.
        /// </summary>
        public static string Global_Error_GuestsNotAllowed {
            get {
                return ResourceManager.GetString("Global_Error_GuestsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Data is Empty.
        /// </summary>
        public static string Global_Error_ImageEmpty {
            get {
                return ResourceManager.GetString("Global_Error_ImageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image format is not valid.
        /// </summary>
        public static string Global_Error_ImageInvalid {
            get {
                return ResourceManager.GetString("Global_Error_ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Too Large :/.
        /// </summary>
        public static string Global_Error_ImageTooLarge {
            get {
                return ResourceManager.GetString("Global_Error_ImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Global_Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Global_Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is invalid or has expired. Please log in again.
        /// </summary>
        public static string Global_Error_InvalidToken {
            get {
                return ResourceManager.GetString("Global_Error_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username is not valid or is already taken. Please try another.
        /// </summary>
        public static string Global_Error_InvalidUsername {
            get {
                return ResourceManager.GetString("Global_Error_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not have a valid format.
        /// </summary>
        public static string Global_Error_PasswordInvalid {
            get {
                return ResourceManager.GetString("Global_Error_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registration request was found for this email.
        /// </summary>
        public static string Global_Error_RegistrationNotFound {
            get {
                return ResourceManager.GetString("Global_Error_RegistrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired.
        /// </summary>
        public static string Global_Error_SessionExpired {
            get {
                return ResourceManager.GetString("Global_Error_SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Global_Error_UserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("Global_Error_UserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is already in use. Please choose another.
        /// </summary>
        public static string Global_Error_UsernameInUse {
            get {
                return ResourceManager.GetString("Global_Error_UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string Global_Error_UserNotFound {
            get {
                return ResourceManager.GetString("Global_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pangolin-Regular.ttf #Pangolin.
        /// </summary>
        public static string Global_FontName {
            get {
                return ResourceManager.GetString("Global_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Global_Label_Avatar {
            get {
                return ResourceManager.GetString("Global_Label_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Global_Label_Cards {
            get {
                return ResourceManager.GetString("Global_Label_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Global_Label_Confirm {
            get {
                return ResourceManager.GetString("Global_Label_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string Global_Label_ConnectionFailed {
            get {
                return ResourceManager.GetString("Global_Label_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty;.
        /// </summary>
        public static string Global_Label_Difficulty {
            get {
                return ResourceManager.GetString("Global_Label_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Global_Label_Email {
            get {
                return ResourceManager.GetString("Global_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 6 digit code:.
        /// </summary>
        public static string Global_Label_EnterCode {
            get {
                return ResourceManager.GetString("Global_Label_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an username:.
        /// </summary>
        public static string Global_Label_EnterUsername {
            get {
                return ResourceManager.GetString("Global_Label_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Last Name:.
        /// </summary>
        public static string Global_Label_LastName {
            get {
                return ResourceManager.GetString("Global_Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Name:.
        /// </summary>
        public static string Global_Label_Name {
            get {
                return ResourceManager.GetString("Global_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Registration.
        /// </summary>
        public static string Global_Label_NoRegister {
            get {
                return ResourceManager.GetString("Global_Label_NoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cards.
        /// </summary>
        public static string Global_Label_NumberOfCards {
            get {
                return ResourceManager.GetString("Global_Label_NumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Global_Label_Offline {
            get {
                return ResourceManager.GetString("Global_Label_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Global_Label_Online {
            get {
                return ResourceManager.GetString("Global_Label_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Global_Label_Password {
            get {
                return ResourceManager.GetString("Global_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered email.
        /// </summary>
        public static string Global_Label_RegisteredEmail {
            get {
                return ResourceManager.GetString("Global_Label_RegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Global_Label_Score {
            get {
                return ResourceManager.GetString("Global_Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Global_Label_Seconds {
            get {
                return ResourceManager.GetString("Global_Label_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Global_Label_Status {
            get {
                return ResourceManager.GetString("Global_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer:.
        /// </summary>
        public static string Global_Label_Time {
            get {
                return ResourceManager.GetString("Global_Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Limit:.
        /// </summary>
        public static string Global_Label_TimerLimit {
            get {
                return ResourceManager.GetString("Global_Label_TimerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Global_Label_Username {
            get {
                return ResourceManager.GetString("Global_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to end the account session?.
        /// </summary>
        public static string Global_Message_CloseSession {
            get {
                return ResourceManager.GetString("Global_Message_CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit the game?.
        /// </summary>
        public static string Global_Message_ExitGame {
            get {
                return ResourceManager.GetString("Global_Message_ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        public static string Global_Message_Welcome {
            get {
                return ResourceManager.GetString("Global_Message_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Guest).
        /// </summary>
        public static string Global_Player_GuestSuffix {
            get {
                return ResourceManager.GetString("Global_Player_GuestSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error. The network may be unstable.
        /// </summary>
        public static string Global_ServiceError_NetworkDown {
            get {
                return ResourceManager.GetString("Global_ServiceError_NetworkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server. Please check your connection.
        /// </summary>
        public static string Global_ServiceError_Offline {
            get {
                return ResourceManager.GetString("Global_ServiceError_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        public static string Global_ServiceError_Unknown {
            get {
                return ResourceManager.GetString("Global_ServiceError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string Global_Title_AppError {
            get {
                return ResourceManager.GetString("Global_Title_AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Global_Title_Chat {
            get {
                return ResourceManager.GetString("Global_Title_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Global_Title_Confirm {
            get {
                return ResourceManager.GetString("Global_Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Settings.
        /// </summary>
        public static string Global_Title_CustomDifficulty {
            get {
                return ResourceManager.GetString("Global_Title_CustomDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Global_Title_Error {
            get {
                return ResourceManager.GetString("Global_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Game.
        /// </summary>
        public static string Global_Title_ExitGame {
            get {
                return ResourceManager.GetString("Global_Title_ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Global_Title_Information {
            get {
                return ResourceManager.GetString("Global_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string Global_Title_Lobby {
            get {
                return ResourceManager.GetString("Global_Title_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as a successful guest.
        /// </summary>
        public static string Global_Title_LoginAsGuestSuccess {
            get {
                return ResourceManager.GetString("Global_Title_LoginAsGuestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string Global_Title_LoginFailed {
            get {
                return ResourceManager.GetString("Global_Title_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        public static string Global_Title_LoginSuccess {
            get {
                return ResourceManager.GetString("Global_Title_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Over.
        /// </summary>
        public static string Global_Title_MatchOver {
            get {
                return ResourceManager.GetString("Global_Title_MatchOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        public static string Global_Title_Multiplayer {
            get {
                return ResourceManager.GetString("Global_Title_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error .
        /// </summary>
        public static string Global_Title_NetworkError {
            get {
                return ResourceManager.GetString("Global_Title_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not available.
        /// </summary>
        public static string Global_Title_NotAvailableFunction {
            get {
                return ResourceManager.GetString("Global_Title_NotAvailableFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Global_Title_Players {
            get {
                return ResourceManager.GetString("Global_Title_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Offline.
        /// </summary>
        public static string Global_Title_ServerOffline {
            get {
                return ResourceManager.GetString("Global_Title_ServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleplayer.
        /// </summary>
        public static string Global_Title_Singleplayer {
            get {
                return ResourceManager.GetString("Global_Title_Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Global_Title_Success {
            get {
                return ResourceManager.GetString("Global_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Global_Title_Warning {
            get {
                return ResourceManager.GetString("Global_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot be empty.
        /// </summary>
        public static string Global_ValidationCode_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not exceed 6 characters.
        /// </summary>
        public static string Global_ValidationCode_LengthInvalid {
            get {
                return ResourceManager.GetString("Global_ValidationCode_LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code should only contain numbers.
        /// </summary>
        public static string Global_ValidationCode_NotNumeric {
            get {
                return ResourceManager.GetString("Global_ValidationCode_NotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string Global_ValidationEmail_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationEmail_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid. Please enter a valid address.
        /// </summary>
        public static string Global_ValidationEmail_InvalidFormat {
            get {
                return ResourceManager.GetString("Global_ValidationEmail_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string Global_ValidationPassword_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 and 20 characters long.
        /// </summary>
        public static string Global_ValidationPassword_LengthInvalid {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number.
        /// </summary>
        public static string Global_ValidationPassword_MissingDigit {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter.
        /// </summary>
        public static string Global_ValidationPassword_MissingLower {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter.
        /// </summary>
        public static string Global_ValidationPassword_MissingUpper {
            get {
                return ResourceManager.GetString("Global_ValidationPassword_MissingUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        public static string Global_ValidationUsername_Empty {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must not contain spaces; use - or _ instead.
        /// </summary>
        public static string Global_ValidationUsername_InvalidChars {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be 30 characters or less.
        /// </summary>
        public static string Global_ValidationUsername_TooLong {
            get {
                return ResourceManager.GetString("Global_ValidationUsername_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send invitation.
        /// </summary>
        public static string HostLobby_Button_SendInvitation {
            get {
                return ResourceManager.GetString("HostLobby_Button_SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create lobby.
        /// </summary>
        public static string HostLobby_Error_CreateFailed {
            get {
                return ResourceManager.GetString("HostLobby_Error_CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string HostLobby_Error_EmailInvalid {
            get {
                return ResourceManager.GetString("HostLobby_Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send invitation. Please try again later.
        /// </summary>
        public static string HostLobby_Error_InviteFailed {
            get {
                return ResourceManager.GetString("HostLobby_Error_InviteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string HostLobby_Label_Available {
            get {
                return ResourceManager.GetString("HostLobby_Label_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your friend&apos;s email:.
        /// </summary>
        public static string HostLobby_Label_EnterFriendEmail {
            get {
                return ResourceManager.GetString("HostLobby_Label_EnterFriendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code:.
        /// </summary>
        public static string HostLobby_Label_GameCode {
            get {
                return ResourceManager.GetString("HostLobby_Label_GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time per Turn:.
        /// </summary>
        public static string HostLobby_Label_TimePerTurn {
            get {
                return ResourceManager.GetString("HostLobby_Label_TimePerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent successfully to {0}.
        /// </summary>
        public static string HostLobby_Message_InviteSent {
            get {
                return ResourceManager.GetString("HostLobby_Message_InviteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        public static string HostLobby_Title_GameSettings {
            get {
                return ResourceManager.GetString("HostLobby_Title_GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends.
        /// </summary>
        public static string HostLobby_Title_InviteFriends {
            get {
                return ResourceManager.GetString("HostLobby_Title_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your friend&apos;s email:.
        /// </summary>
        public static string InviteFriendDialog_Label_EnterEmail {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Label_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default mail application was found installed on the system :(.
        /// </summary>
        public static string InviteFriendDialog_Label_ErrorAppEmail {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Label_ErrorAppEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeey budy, join my game so we can play :D The Lobby code is:.
        /// </summary>
        public static string InviteFriendDialog_Message_BodyEmail {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Message_BodyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email .
        /// </summary>
        public static string InviteFriendDialog_Message_EnterEmail {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Message_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friend.
        /// </summary>
        public static string InviteFriendDialog_Title_InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Title_InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join my Memory Game Match!.
        /// </summary>
        public static string InviteFriendDialog_Title_SubjectEmail {
            get {
                return ResourceManager.GetString("InviteFriendDialog_Title_SubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friend.
        /// </summary>
        public static string Lobby_Button_Invite {
            get {
                return ResourceManager.GetString("Lobby_Button_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests are not allowed to send chat messages.
        /// </summary>
        public static string Lobby_Error_GuestChat {
            get {
                return ResourceManager.GetString("Lobby_Error_GuestChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to join lobby. Invalid code or lobby is full.
        /// </summary>
        public static string Lobby_Error_JoinFailed {
            get {
                return ResourceManager.GetString("Lobby_Error_JoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send chat message.
        /// </summary>
        public static string Lobby_Error_SendChatFailed {
            get {
                return ResourceManager.GetString("Lobby_Error_SendChatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Code:.
        /// </summary>
        public static string Lobby_Label_GameCode {
            get {
                return ResourceManager.GetString("Lobby_Label_GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby successfully created!.
        /// </summary>
        public static string Lobby_Message_CreateSuccess {
            get {
                return ResourceManager.GetString("Lobby_Message_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the lobby.
        /// </summary>
        public static string Lobby_Notification_PlayerJoined {
            get {
                return ResourceManager.GetString("Lobby_Notification_PlayerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the lobby.
        /// </summary>
        public static string Lobby_Notification_PlayerLeft {
            get {
                return ResourceManager.GetString("Lobby_Notification_PlayerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [System].
        /// </summary>
        public static string Lobby_Notification_System {
            get {
                return ResourceManager.GetString("Lobby_Notification_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string MainMenu_Button_Gallery {
            get {
                return ResourceManager.GetString("MainMenu_Button_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load match history.
        /// </summary>
        public static string MatchHistory_Label_ErrorHistory {
            get {
                return ResourceManager.GetString("MatchHistory_Label_ErrorHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string MatchSummary_Label_Lost {
            get {
                return ResourceManager.GetString("MatchSummary_Label_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: .
        /// </summary>
        public static string MatchSummary_Label_Player {
            get {
                return ResourceManager.GetString("MatchSummary_Label_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary: .
        /// </summary>
        public static string MatchSummary_Label_Summary {
            get {
                return ResourceManager.GetString("MatchSummary_Label_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining:.
        /// </summary>
        public static string MatchSummary_Label_TimeRemaining {
            get {
                return ResourceManager.GetString("MatchSummary_Label_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Win! :D.
        /// </summary>
        public static string MatchSummary_Label_Win {
            get {
                return ResourceManager.GetString("MatchSummary_Label_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create lobby.
        /// </summary>
        public static string MultiplayerMenu_Button_CreateLobby {
            get {
                return ResourceManager.GetString("MultiplayerMenu_Button_CreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string PlayerProfile_Button_Friends {
            get {
                return ResourceManager.GetString("PlayerProfile_Button_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string PlayerProfile_Button_Statistics {
            get {
                return ResourceManager.GetString("PlayerProfile_Button_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue:.
        /// </summary>
        public static string PlayerProfile_Label_Date {
            get {
                return ResourceManager.GetString("PlayerProfile_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string PlayerProfile_Label_Email {
            get {
                return ResourceManager.GetString("PlayerProfile_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PlayerProfile_Label_Name {
            get {
                return ResourceManager.GetString("PlayerProfile_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Networks:.
        /// </summary>
        public static string PlayerProfile_Label_Social {
            get {
                return ResourceManager.GetString("PlayerProfile_Label_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellooo {0}! To access your friends, statistics, and profile, you need to register your account with an email address.
        /// </summary>
        public static string PlayerProfile_Message_NotAvaible {
            get {
                return ResourceManager.GetString("PlayerProfile_Message_NotAvaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. The email may already be in use.
        /// </summary>
        public static string RegisterAccount_Message_Failed {
            get {
                return ResourceManager.GetString("RegisterAccount_Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful! A verification code has been sent to your email.
        /// </summary>
        public static string RegisterAccount_Message_Success {
            get {
                return ResourceManager.GetString("RegisterAccount_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Account.
        /// </summary>
        public static string RegisterAccount_Title_LinkAccount {
            get {
                return ResourceManager.GetString("RegisterAccount_Title_LinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot report yourself.
        /// </summary>
        public static string ReportUserDialog_Error_AutoReport {
            get {
                return ResourceManager.GetString("ReportUserDialog_Error_AutoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to report this player for bad behavior?.
        /// </summary>
        public static string ReportUserDialog_Message_Report {
            get {
                return ResourceManager.GetString("ReportUserDialog_Message_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User reported successfully. Admins will review the case :).
        /// </summary>
        public static string ReportUserDialog_Message_ReportSuccess {
            get {
                return ResourceManager.GetString("ReportUserDialog_Message_ReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Player .
        /// </summary>
        public static string ReportUserDialog_Title_Report {
            get {
                return ResourceManager.GetString("ReportUserDialog_Title_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Sent.
        /// </summary>
        public static string ReportUserDialog_Title_ReportSuccess {
            get {
                return ResourceManager.GetString("ReportUserDialog_Title_ReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string SelectDifficulty_Button_Easy {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string SelectDifficulty_Button_Hard {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SelectDifficulty_Button_Normal {
            get {
                return ResourceManager.GetString("SelectDifficulty_Button_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Settings_Label_Audio {
            get {
                return ResourceManager.GetString("Settings_Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Settings_Label_General {
            get {
                return ResourceManager.GetString("Settings_Label_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Label_Language {
            get {
                return ResourceManager.GetString("Settings_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        public static string Settings_Label_Music {
            get {
                return ResourceManager.GetString("Settings_Label_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFX Volume.
        /// </summary>
        public static string Settings_Label_SFX {
            get {
                return ResourceManager.GetString("Settings_Label_SFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (US).
        /// </summary>
        public static string Settings_Language_EnUS {
            get {
                return ResourceManager.GetString("Settings_Language_EnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (MX).
        /// </summary>
        public static string Settings_Language_EsMX {
            get {
                return ResourceManager.GetString("Settings_Language_EsMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png;*.bmp.
        /// </summary>
        public static string SetupProfile_Dialog_Filter {
            get {
                return ResourceManager.GetString("SetupProfile_Dialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile Image.
        /// </summary>
        public static string SetupProfile_Dialog_Title {
            get {
                return ResourceManager.GetString("SetupProfile_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load image: {0}.
        /// </summary>
        public static string SetupProfile_Error_ImageLoad {
            get {
                return ResourceManager.GetString("SetupProfile_Error_ImageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an avatar:.
        /// </summary>
        public static string SetupProfile_Label_SelectAvatar {
            get {
                return ResourceManager.GetString("SetupProfile_Label_SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile setup complete! Welcome.
        /// </summary>
        public static string SetupProfile_Message_Success {
            get {
                return ResourceManager.GetString("SetupProfile_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try faster next time.
        /// </summary>
        public static string Singleplayer_Label_TimeOver {
            get {
                return ResourceManager.GetString("Singleplayer_Label_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s Up! :(.
        /// </summary>
        public static string Singleplayer_Title_TimeOver {
            get {
                return ResourceManager.GetString("Singleplayer_Title_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pairs Found! :D.
        /// </summary>
        public static string Singleplayer_Title_Won {
            get {
                return ResourceManager.GetString("Singleplayer_Title_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already friends :&gt;.
        /// </summary>
        public static string Social_Error_AlreadyFriends {
            get {
                return ResourceManager.GetString("Social_Error_AlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request already pending.
        /// </summary>
        public static string Social_Error_RequestExists {
            get {
                return ResourceManager.GetString("Social_Error_RequestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add yourself.
        /// </summary>
        public static string Social_Error_SelfAdd {
            get {
                return ResourceManager.GetString("Social_Error_SelfAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string StatsHistory_Label_Date {
            get {
                return ResourceManager.GetString("StatsHistory_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string StatsHistory_Label_Score {
            get {
                return ResourceManager.GetString("StatsHistory_Label_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string StatsHistory_Label_Winner {
            get {
                return ResourceManager.GetString("StatsHistory_Label_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match History.
        /// </summary>
        public static string StatsHistory_Title_StatsHistory {
            get {
                return ResourceManager.GetString("StatsHistory_Title_StatsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Game.
        /// </summary>
        public static string TitleScreen_Label_Memorama {
            get {
                return ResourceManager.GetString("TitleScreen_Label_Memorama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code forwarded.
        /// </summary>
        public static string Verify_Message_CodeResent {
            get {
                return ResourceManager.GetString("Verify_Message_CodeResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send again?.
        /// </summary>
        public static string VerifyCode_Button_SentAgain {
            get {
                return ResourceManager.GetString("VerifyCode_Button_SentAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification email was sent to:.
        /// </summary>
        public static string VerifyCode_Label_SentTo {
            get {
                return ResourceManager.GetString("VerifyCode_Label_SentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully verified! 
        ///You need to log in with your new account :).
        /// </summary>
        public static string VerifyCode_Message_GuestSuccess {
            get {
                return ResourceManager.GetString("VerifyCode_Message_GuestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully verified!.
        /// </summary>
        public static string VerifyCode_Message_Success {
            get {
                return ResourceManager.GetString("VerifyCode_Message_Success", resourceCulture);
            }
        }
    }
}
