//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class amigo
    {
        public int idAmigo { get; set; }
        public string nombre { get; set; }
        public int idUsuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
