//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int cardId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int inventoryId { get; set; }
    
        public virtual inventory inventory { get; set; }
    }
}
