//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int requestId { get; set; }
        public int senderId { get; set; }
        public int receiverId { get; set; }
        public Nullable<System.DateTime> sentAt { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
