//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial
    {
        public int idUsuario { get; set; }
        public int idPartida { get; set; }
        public int puntuacion { get; set; }
        public int idGanador { get; set; }
        public string usernameGanador { get; set; }
    
        public virtual partida partida { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
