//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchHistory
    {
        public int userId { get; set; }
        public int matchId { get; set; }
        public int score { get; set; }
        public int winnerId { get; set; }
    
        public virtual match match { get; set; }
        public virtual user user { get; set; }
    }
}
