//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class pendingRegistration
    {
        public int pendingRegistrationId { get; set; }
        public string email { get; set; }
        public string pin { get; set; }
        public System.DateTime expirationTime { get; set; }
        public System.DateTime createdAt { get; set; }
        public string hashedPassword { get; set; }
    }
}
