//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class pendingRegistration
    {
        public int pendingRegistrationId { get; set; }
        public string email { get; set; }
        public string pin { get; set; }
        public System.DateTime expirationTime { get; set; }
        public System.DateTime createdAt { get; set; }
        public string hashedPassword { get; set; }
    }
}
