//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingRegistrations
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Pin { get; set; }
        public System.DateTime ExpiryTime { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string HashedPassword { get; set; }
    }
}
