//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialNetwork
    {
        public int socialNetworkId { get; set; }
        public string account { get; set; }
        public int userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
