//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class userSession
    {
        public string token { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime expiresAt { get; set; }
        public int userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
