//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestRegistration", ReplyAction="http://tempuri.org/IUserService/RequestRegistrationResponse")]
        bool RequestRegistration(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RequestRegistration", ReplyAction="http://tempuri.org/IUserService/RequestRegistrationResponse")]
        System.Threading.Tasks.Task<bool> RequestRegistrationAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyRegistrationResponse")]
        bool VerifyRegistration(string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyRegistrationResponse")]
        System.Threading.Tasks.Task<bool> VerifyRegistrationAsync(string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserProfile", ReplyAction="http://tempuri.org/IUserService/UpdateUserProfileResponse")]
        bool UpdateUserProfile(string email, string username, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserProfile", ReplyAction="http://tempuri.org/IUserService/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserProfileAsync(string email, string username, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        bool Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Client.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Client.UserServiceReference.IUserService>, Client.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RequestRegistration(string email, string password) {
            return base.Channel.RequestRegistration(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> RequestRegistrationAsync(string email, string password) {
            return base.Channel.RequestRegistrationAsync(email, password);
        }
        
        public bool VerifyRegistration(string email, string pin) {
            return base.Channel.VerifyRegistration(email, pin);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyRegistrationAsync(string email, string pin) {
            return base.Channel.VerifyRegistrationAsync(email, pin);
        }
        
        public bool UpdateUserProfile(string email, string username, byte[] avatar) {
            return base.Channel.UpdateUserProfile(email, username, avatar);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserProfileAsync(string email, string username, byte[] avatar) {
            return base.Channel.UpdateUserProfileAsync(email, username, avatar);
        }
        
        public bool Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
    }
}
