//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.UserServiceReference.LoginResponse))]
    public partial class ResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageKey {
            get {
                return this.MessageKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageKeyField, value) != true)) {
                    this.MessageKeyField = value;
                    this.RaisePropertyChanged("MessageKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : Client.UserServiceReference.ResponseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.UserServiceReference.UserDTO UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.UserServiceReference.UserDTO User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.UserServiceReference.SocialNetworkDTO[] SocialNetworksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.UserServiceReference.SocialNetworkDTO[] SocialNetworks {
            get {
                return this.SocialNetworksField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialNetworksField, value) != true)) {
                    this.SocialNetworksField = value;
                    this.RaisePropertyChanged("SocialNetworks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocialNetworkDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class SocialNetworkDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SocialNetworkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SocialNetworkId {
            get {
                return this.SocialNetworkIdField;
            }
            set {
                if ((this.SocialNetworkIdField.Equals(value) != true)) {
                    this.SocialNetworkIdField = value;
                    this.RaisePropertyChanged("SocialNetworkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class FriendDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class FriendRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SenderAvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SenderAvatar {
            get {
                return this.SenderAvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAvatarField, value) != true)) {
                    this.SenderAvatarField = value;
                    this.RaisePropertyChanged("SenderAvatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername {
            get {
                return this.SenderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUsernameField, value) != true)) {
                    this.SenderUsernameField = value;
                    this.RaisePropertyChanged("SenderUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/Server.SessionService")]
    [System.SerializableAttribute()]
    public partial class MatchHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerName {
            get {
                return this.WinnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerNameField, value) != true)) {
                    this.WinnerNameField = value;
                    this.RaisePropertyChanged("WinnerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService", CallbackContract=typeof(Client.UserServiceReference.IUserServiceCallback))]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/StartRegistration", ReplyAction="http://tempuri.org/IUserService/StartRegistrationResponse")]
        Client.UserServiceReference.ResponseDTO StartRegistration(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/StartRegistration", ReplyAction="http://tempuri.org/IUserService/StartRegistrationResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> StartRegistrationAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyRegistrationResponse")]
        Client.UserServiceReference.ResponseDTO VerifyRegistration(string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyRegistrationResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> VerifyRegistrationAsync(string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ResendVerificationCode", ReplyAction="http://tempuri.org/IUserService/ResendVerificationCodeResponse")]
        Client.UserServiceReference.ResponseDTO ResendVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ResendVerificationCode", ReplyAction="http://tempuri.org/IUserService/ResendVerificationCodeResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ResendVerificationCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FinalizeRegistration", ReplyAction="http://tempuri.org/IUserService/FinalizeRegistrationResponse")]
        Client.UserServiceReference.LoginResponse FinalizeRegistration(string email, string username, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FinalizeRegistration", ReplyAction="http://tempuri.org/IUserService/FinalizeRegistrationResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> FinalizeRegistrationAsync(string email, string username, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        Client.UserServiceReference.LoginResponse Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RenewSession", ReplyAction="http://tempuri.org/IUserService/RenewSessionResponse")]
        Client.UserServiceReference.LoginResponse RenewSession(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RenewSession", ReplyAction="http://tempuri.org/IUserService/RenewSessionResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> RenewSessionAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAvatar", ReplyAction="http://tempuri.org/IUserService/GetUserAvatarResponse")]
        byte[] GetUserAvatar(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserAvatar", ReplyAction="http://tempuri.org/IUserService/GetUserAvatarResponse")]
        System.Threading.Tasks.Task<byte[]> GetUserAvatarAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserAvatar", ReplyAction="http://tempuri.org/IUserService/UpdateUserAvatarResponse")]
        Client.UserServiceReference.ResponseDTO UpdateUserAvatar(string email, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUserAvatar", ReplyAction="http://tempuri.org/IUserService/UpdateUserAvatarResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> UpdateUserAvatarAsync(string email, byte[] avatar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        Client.UserServiceReference.ResponseDTO ChangePassword(string email, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ChangePasswordAsync(string email, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeUsername", ReplyAction="http://tempuri.org/IUserService/ChangeUsernameResponse")]
        Client.UserServiceReference.ResponseDTO ChangeUsername(string email, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangeUsername", ReplyAction="http://tempuri.org/IUserService/ChangeUsernameResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ChangeUsernameAsync(string email, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdatePersonalInfo", ReplyAction="http://tempuri.org/IUserService/UpdatePersonalInfoResponse")]
        Client.UserServiceReference.ResponseDTO UpdatePersonalInfo(string email, string name, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdatePersonalInfo", ReplyAction="http://tempuri.org/IUserService/UpdatePersonalInfoResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> UpdatePersonalInfoAsync(string email, string name, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSocialNetwork", ReplyAction="http://tempuri.org/IUserService/AddSocialNetworkResponse")]
        Client.UserServiceReference.ResponseDTO AddSocialNetwork(string token, string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddSocialNetwork", ReplyAction="http://tempuri.org/IUserService/AddSocialNetworkResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> AddSocialNetworkAsync(string token, string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSocialNetwork", ReplyAction="http://tempuri.org/IUserService/RemoveSocialNetworkResponse")]
        Client.UserServiceReference.ResponseDTO RemoveSocialNetwork(string token, int socialNetworkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveSocialNetwork", ReplyAction="http://tempuri.org/IUserService/RemoveSocialNetworkResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> RemoveSocialNetworkAsync(string token, int socialNetworkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginAsGuest", ReplyAction="http://tempuri.org/IUserService/LoginAsGuestResponse")]
        Client.UserServiceReference.LoginResponse LoginAsGuest(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginAsGuest", ReplyAction="http://tempuri.org/IUserService/LoginAsGuestResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> LoginAsGuestAsync(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LogoutGuest", ReplyAction="http://tempuri.org/IUserService/LogoutGuestResponse")]
        void LogoutGuest(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LogoutGuest", ReplyAction="http://tempuri.org/IUserService/LogoutGuestResponse")]
        System.Threading.Tasks.Task LogoutGuestAsync(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Logout", ReplyAction="http://tempuri.org/IUserService/LogoutResponse")]
        void Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Logout", ReplyAction="http://tempuri.org/IUserService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InitiateGuestRegistration", ReplyAction="http://tempuri.org/IUserService/InitiateGuestRegistrationResponse")]
        Client.UserServiceReference.ResponseDTO InitiateGuestRegistration(int guestUserId, string newEmail, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InitiateGuestRegistration", ReplyAction="http://tempuri.org/IUserService/InitiateGuestRegistrationResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> InitiateGuestRegistrationAsync(int guestUserId, string newEmail, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyGuestRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyGuestRegistrationResponse")]
        Client.UserServiceReference.ResponseDTO VerifyGuestRegistration(int guestUserId, string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyGuestRegistration", ReplyAction="http://tempuri.org/IUserService/VerifyGuestRegistrationResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> VerifyGuestRegistrationAsync(int guestUserId, string email, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetFriendsList", ReplyAction="http://tempuri.org/IUserService/GetFriendsListResponse")]
        Client.UserServiceReference.FriendDTO[] GetFriendsList(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetFriendsList", ReplyAction="http://tempuri.org/IUserService/GetFriendsListResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.FriendDTO[]> GetFriendsListAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendFriendRequest", ReplyAction="http://tempuri.org/IUserService/SendFriendRequestResponse")]
        Client.UserServiceReference.ResponseDTO SendFriendRequest(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendFriendRequest", ReplyAction="http://tempuri.org/IUserService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> SendFriendRequestAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPendingRequests", ReplyAction="http://tempuri.org/IUserService/GetPendingRequestsResponse")]
        Client.UserServiceReference.FriendRequestDTO[] GetPendingRequests(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPendingRequests", ReplyAction="http://tempuri.org/IUserService/GetPendingRequestsResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.FriendRequestDTO[]> GetPendingRequestsAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveFriend", ReplyAction="http://tempuri.org/IUserService/RemoveFriendResponse")]
        Client.UserServiceReference.ResponseDTO RemoveFriend(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveFriend", ReplyAction="http://tempuri.org/IUserService/RemoveFriendResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> RemoveFriendAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AnswerFriendRequest", ReplyAction="http://tempuri.org/IUserService/AnswerFriendRequestResponse")]
        Client.UserServiceReference.ResponseDTO AnswerFriendRequest(string token, int requestId, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AnswerFriendRequest", ReplyAction="http://tempuri.org/IUserService/AnswerFriendRequestResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> AnswerFriendRequestAsync(string token, int requestId, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetMatchHistory", ReplyAction="http://tempuri.org/IUserService/GetMatchHistoryResponse")]
        Client.UserServiceReference.MatchHistoryDTO[] GetMatchHistory(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetMatchHistory", ReplyAction="http://tempuri.org/IUserService/GetMatchHistoryResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.MatchHistoryDTO[]> GetMatchHistoryAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReportUser", ReplyAction="http://tempuri.org/IUserService/ReportUserResponse")]
        Client.UserServiceReference.ResponseDTO ReportUser(string token, string targetUser, int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReportUser", ReplyAction="http://tempuri.org/IUserService/ReportUserResponse")]
        System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ReportUserAsync(string token, string targetUser, int matchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/ForceLogout")]
        void ForceLogout(string reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Client.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.DuplexClientBase<Client.UserServiceReference.IUserService>, Client.UserServiceReference.IUserService {
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Client.UserServiceReference.ResponseDTO StartRegistration(string email, string password) {
            return base.Channel.StartRegistration(email, password);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> StartRegistrationAsync(string email, string password) {
            return base.Channel.StartRegistrationAsync(email, password);
        }
        
        public Client.UserServiceReference.ResponseDTO VerifyRegistration(string email, string pin) {
            return base.Channel.VerifyRegistration(email, pin);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> VerifyRegistrationAsync(string email, string pin) {
            return base.Channel.VerifyRegistrationAsync(email, pin);
        }
        
        public Client.UserServiceReference.ResponseDTO ResendVerificationCode(string email) {
            return base.Channel.ResendVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ResendVerificationCodeAsync(string email) {
            return base.Channel.ResendVerificationCodeAsync(email);
        }
        
        public Client.UserServiceReference.LoginResponse FinalizeRegistration(string email, string username, byte[] avatar) {
            return base.Channel.FinalizeRegistration(email, username, avatar);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> FinalizeRegistrationAsync(string email, string username, byte[] avatar) {
            return base.Channel.FinalizeRegistrationAsync(email, username, avatar);
        }
        
        public Client.UserServiceReference.LoginResponse Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public Client.UserServiceReference.LoginResponse RenewSession(string token) {
            return base.Channel.RenewSession(token);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> RenewSessionAsync(string token) {
            return base.Channel.RenewSessionAsync(token);
        }
        
        public byte[] GetUserAvatar(string email) {
            return base.Channel.GetUserAvatar(email);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetUserAvatarAsync(string email) {
            return base.Channel.GetUserAvatarAsync(email);
        }
        
        public Client.UserServiceReference.ResponseDTO UpdateUserAvatar(string email, byte[] avatar) {
            return base.Channel.UpdateUserAvatar(email, avatar);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> UpdateUserAvatarAsync(string email, byte[] avatar) {
            return base.Channel.UpdateUserAvatarAsync(email, avatar);
        }
        
        public Client.UserServiceReference.ResponseDTO ChangePassword(string email, string currentPassword, string newPassword) {
            return base.Channel.ChangePassword(email, currentPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ChangePasswordAsync(string email, string currentPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(email, currentPassword, newPassword);
        }
        
        public Client.UserServiceReference.ResponseDTO ChangeUsername(string email, string newUsername) {
            return base.Channel.ChangeUsername(email, newUsername);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ChangeUsernameAsync(string email, string newUsername) {
            return base.Channel.ChangeUsernameAsync(email, newUsername);
        }
        
        public Client.UserServiceReference.ResponseDTO UpdatePersonalInfo(string email, string name, string lastName) {
            return base.Channel.UpdatePersonalInfo(email, name, lastName);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> UpdatePersonalInfoAsync(string email, string name, string lastName) {
            return base.Channel.UpdatePersonalInfoAsync(email, name, lastName);
        }
        
        public Client.UserServiceReference.ResponseDTO AddSocialNetwork(string token, string accountName) {
            return base.Channel.AddSocialNetwork(token, accountName);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> AddSocialNetworkAsync(string token, string accountName) {
            return base.Channel.AddSocialNetworkAsync(token, accountName);
        }
        
        public Client.UserServiceReference.ResponseDTO RemoveSocialNetwork(string token, int socialNetworkId) {
            return base.Channel.RemoveSocialNetwork(token, socialNetworkId);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> RemoveSocialNetworkAsync(string token, int socialNetworkId) {
            return base.Channel.RemoveSocialNetworkAsync(token, socialNetworkId);
        }
        
        public Client.UserServiceReference.LoginResponse LoginAsGuest(string guestUsername) {
            return base.Channel.LoginAsGuest(guestUsername);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.LoginResponse> LoginAsGuestAsync(string guestUsername) {
            return base.Channel.LoginAsGuestAsync(guestUsername);
        }
        
        public void LogoutGuest(string sessionToken) {
            base.Channel.LogoutGuest(sessionToken);
        }
        
        public System.Threading.Tasks.Task LogoutGuestAsync(string sessionToken) {
            return base.Channel.LogoutGuestAsync(sessionToken);
        }
        
        public void Logout(string token) {
            base.Channel.Logout(token);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string token) {
            return base.Channel.LogoutAsync(token);
        }
        
        public Client.UserServiceReference.ResponseDTO InitiateGuestRegistration(int guestUserId, string newEmail, string newPassword) {
            return base.Channel.InitiateGuestRegistration(guestUserId, newEmail, newPassword);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> InitiateGuestRegistrationAsync(int guestUserId, string newEmail, string newPassword) {
            return base.Channel.InitiateGuestRegistrationAsync(guestUserId, newEmail, newPassword);
        }
        
        public Client.UserServiceReference.ResponseDTO VerifyGuestRegistration(int guestUserId, string email, string pin) {
            return base.Channel.VerifyGuestRegistration(guestUserId, email, pin);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> VerifyGuestRegistrationAsync(int guestUserId, string email, string pin) {
            return base.Channel.VerifyGuestRegistrationAsync(guestUserId, email, pin);
        }
        
        public Client.UserServiceReference.FriendDTO[] GetFriendsList(string token) {
            return base.Channel.GetFriendsList(token);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.FriendDTO[]> GetFriendsListAsync(string token) {
            return base.Channel.GetFriendsListAsync(token);
        }
        
        public Client.UserServiceReference.ResponseDTO SendFriendRequest(string token, string username) {
            return base.Channel.SendFriendRequest(token, username);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> SendFriendRequestAsync(string token, string username) {
            return base.Channel.SendFriendRequestAsync(token, username);
        }
        
        public Client.UserServiceReference.FriendRequestDTO[] GetPendingRequests(string token) {
            return base.Channel.GetPendingRequests(token);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.FriendRequestDTO[]> GetPendingRequestsAsync(string token) {
            return base.Channel.GetPendingRequestsAsync(token);
        }
        
        public Client.UserServiceReference.ResponseDTO RemoveFriend(string token, string username) {
            return base.Channel.RemoveFriend(token, username);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> RemoveFriendAsync(string token, string username) {
            return base.Channel.RemoveFriendAsync(token, username);
        }
        
        public Client.UserServiceReference.ResponseDTO AnswerFriendRequest(string token, int requestId, bool accept) {
            return base.Channel.AnswerFriendRequest(token, requestId, accept);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> AnswerFriendRequestAsync(string token, int requestId, bool accept) {
            return base.Channel.AnswerFriendRequestAsync(token, requestId, accept);
        }
        
        public Client.UserServiceReference.MatchHistoryDTO[] GetMatchHistory(string token) {
            return base.Channel.GetMatchHistory(token);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.MatchHistoryDTO[]> GetMatchHistoryAsync(string token) {
            return base.Channel.GetMatchHistoryAsync(token);
        }
        
        public Client.UserServiceReference.ResponseDTO ReportUser(string token, string targetUser, int matchId) {
            return base.Channel.ReportUser(token, targetUser, matchId);
        }
        
        public System.Threading.Tasks.Task<Client.UserServiceReference.ResponseDTO> ReportUserAsync(string token, string targetUser, int matchId) {
            return base.Channel.ReportUserAsync(token, targetUser, matchId);
        }
    }
}
