//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GameLobbyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyPlayerInfo", Namespace="http://schemas.datacontract.org/2004/07/Server.LobbyService")]
    [System.SerializableAttribute()]
    public partial class LobbyPlayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JoinedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGuest {
            get {
                return this.IsGuestField;
            }
            set {
                if ((this.IsGuestField.Equals(value) != true)) {
                    this.IsGuestField = value;
                    this.RaisePropertyChanged("IsGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JoinedAt {
            get {
                return this.JoinedAtField;
            }
            set {
                if ((this.JoinedAtField.Equals(value) != true)) {
                    this.JoinedAtField = value;
                    this.RaisePropertyChanged("JoinedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameLobbyServiceReference.IGameLobbyService", CallbackContract=typeof(Client.GameLobbyServiceReference.IGameLobbyServiceCallback))]
    public interface IGameLobbyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/JoinLobby", ReplyAction="http://tempuri.org/IGameLobbyService/JoinLobbyResponse")]
        bool JoinLobby(string token, string gameCode, bool isGuest, string guestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/JoinLobby", ReplyAction="http://tempuri.org/IGameLobbyService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinLobbyAsync(string token, string gameCode, bool isGuest, string guestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/LeaveLobby", ReplyAction="http://tempuri.org/IGameLobbyService/LeaveLobbyResponse")]
        void LeaveLobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/LeaveLobby", ReplyAction="http://tempuri.org/IGameLobbyService/LeaveLobbyResponse")]
        System.Threading.Tasks.Task LeaveLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendChatMessage", ReplyAction="http://tempuri.org/IGameLobbyService/SendChatMessageResponse")]
        void SendChatMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendChatMessage", ReplyAction="http://tempuri.org/IGameLobbyService/SendChatMessageResponse")]
        System.Threading.Tasks.Task SendChatMessageAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameLobbyServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/ReceiveChatMessage")]
        void ReceiveChatMessage(string senderName, string message, bool isNotification);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/PlayerJoined")]
        void PlayerJoined(string playerNmae, bool isGuest);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/playerLeft")]
        void playerLeft(string playerNmae);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/UpdatePlayerList")]
        void UpdatePlayerList(Client.GameLobbyServiceReference.LobbyPlayerInfo[] players);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameLobbyServiceChannel : Client.GameLobbyServiceReference.IGameLobbyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameLobbyServiceClient : System.ServiceModel.DuplexClientBase<Client.GameLobbyServiceReference.IGameLobbyService>, Client.GameLobbyServiceReference.IGameLobbyService {
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool JoinLobby(string token, string gameCode, bool isGuest, string guestName) {
            return base.Channel.JoinLobby(token, gameCode, isGuest, guestName);
        }
        
        public System.Threading.Tasks.Task<bool> JoinLobbyAsync(string token, string gameCode, bool isGuest, string guestName) {
            return base.Channel.JoinLobbyAsync(token, gameCode, isGuest, guestName);
        }
        
        public void LeaveLobby() {
            base.Channel.LeaveLobby();
        }
        
        public System.Threading.Tasks.Task LeaveLobbyAsync() {
            return base.Channel.LeaveLobbyAsync();
        }
        
        public void SendChatMessage(string message) {
            base.Channel.SendChatMessage(message);
        }
        
        public System.Threading.Tasks.Task SendChatMessageAsync(string message) {
            return base.Channel.SendChatMessageAsync(message);
        }
    }
}
