//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.GameLobbyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameSettings", Namespace="http://schemas.datacontract.org/2004/07/Server.GameService")]
    [System.SerializableAttribute()]
    public partial class GameSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnTimeSecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardCount {
            get {
                return this.CardCountField;
            }
            set {
                if ((this.CardCountField.Equals(value) != true)) {
                    this.CardCountField = value;
                    this.RaisePropertyChanged("CardCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnTimeSeconds {
            get {
                return this.TurnTimeSecondsField;
            }
            set {
                if ((this.TurnTimeSecondsField.Equals(value) != true)) {
                    this.TurnTimeSecondsField = value;
                    this.RaisePropertyChanged("TurnTimeSeconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyPlayerInfo", Namespace="http://schemas.datacontract.org/2004/07/Server.LobbyService")]
    [System.SerializableAttribute()]
    public partial class LobbyPlayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JoinedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGuest {
            get {
                return this.IsGuestField;
            }
            set {
                if ((this.IsGuestField.Equals(value) != true)) {
                    this.IsGuestField = value;
                    this.RaisePropertyChanged("IsGuest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JoinedAt {
            get {
                return this.JoinedAtField;
            }
            set {
                if ((this.JoinedAtField.Equals(value) != true)) {
                    this.JoinedAtField = value;
                    this.RaisePropertyChanged("JoinedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardInfo", Namespace="http://schemas.datacontract.org/2004/07/Server.GameService")]
    [System.SerializableAttribute()]
    public partial class CardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageIdentifier {
            get {
                return this.ImageIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageIdentifierField, value) != true)) {
                    this.ImageIdentifierField = value;
                    this.RaisePropertyChanged("ImageIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameLobbyServiceReference.IGameLobbyService", CallbackContract=typeof(Client.GameLobbyServiceReference.IGameLobbyServiceCallback))]
    public interface IGameLobbyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/Ping", ReplyAction="http://tempuri.org/IGameLobbyService/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/Ping", ReplyAction="http://tempuri.org/IGameLobbyService/PingResponse")]
        System.Threading.Tasks.Task PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/JoinLobby", ReplyAction="http://tempuri.org/IGameLobbyService/JoinLobbyResponse")]
        bool JoinLobby(string token, string gameCode, bool isGuest, string guestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/JoinLobby", ReplyAction="http://tempuri.org/IGameLobbyService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinLobbyAsync(string token, string gameCode, bool isGuest, string guestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/CreateLobby", ReplyAction="http://tempuri.org/IGameLobbyService/CreateLobbyResponse")]
        bool CreateLobby(string token, string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/CreateLobby", ReplyAction="http://tempuri.org/IGameLobbyService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<bool> CreateLobbyAsync(string token, string gameCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/LeaveLobby", ReplyAction="http://tempuri.org/IGameLobbyService/LeaveLobbyResponse")]
        void LeaveLobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/LeaveLobby", ReplyAction="http://tempuri.org/IGameLobbyService/LeaveLobbyResponse")]
        System.Threading.Tasks.Task LeaveLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendChatMessage", ReplyAction="http://tempuri.org/IGameLobbyService/SendChatMessageResponse")]
        void SendChatMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendChatMessage", ReplyAction="http://tempuri.org/IGameLobbyService/SendChatMessageResponse")]
        System.Threading.Tasks.Task SendChatMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/StartGame", ReplyAction="http://tempuri.org/IGameLobbyService/StartGameResponse")]
        void StartGame(Client.GameLobbyServiceReference.GameSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/StartGame", ReplyAction="http://tempuri.org/IGameLobbyService/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(Client.GameLobbyServiceReference.GameSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/FlipCard", ReplyAction="http://tempuri.org/IGameLobbyService/FlipCardResponse")]
        void FlipCard(int cardIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/FlipCard", ReplyAction="http://tempuri.org/IGameLobbyService/FlipCardResponse")]
        System.Threading.Tasks.Task FlipCardAsync(int cardIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/VoteToKick", ReplyAction="http://tempuri.org/IGameLobbyService/VoteToKickResponse")]
        void VoteToKick(string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/VoteToKick", ReplyAction="http://tempuri.org/IGameLobbyService/VoteToKickResponse")]
        System.Threading.Tasks.Task VoteToKickAsync(string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendInvitationEmail", ReplyAction="http://tempuri.org/IGameLobbyService/SendInvitationEmailResponse")]
        bool SendInvitationEmail(string targetEmail, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameLobbyService/SendInvitationEmail", ReplyAction="http://tempuri.org/IGameLobbyService/SendInvitationEmailResponse")]
        System.Threading.Tasks.Task<bool> SendInvitationEmailAsync(string targetEmail, string subject, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameLobbyServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/ReceiveChatMessage")]
        void ReceiveChatMessage(string senderName, string message, bool isNotification);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/PlayerJoined")]
        void PlayerJoined(string playerName, bool isGuest);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/PlayerLeft")]
        void PlayerLeft(string playerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/UpdatePlayerList")]
        void UpdatePlayerList(Client.GameLobbyServiceReference.LobbyPlayerInfo[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/GameStarted")]
        void GameStarted(Client.GameLobbyServiceReference.CardInfo[] gameBoard);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/UpdateTurn")]
        void UpdateTurn(string playerName, int turnTimeInSeconds);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/ShowCard")]
        void ShowCard(int cardIndex, string imageIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/HideCards")]
        void HideCards(int cardIndex1, int cardIndex2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/CardFlipped")]
        void CardFlipped(int cardIndex, int cardIndex2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/SetCardsAsMatched")]
        void SetCardsAsMatched(int cardIndex1, int cardIndex2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/UpdateScore")]
        void UpdateScore(string playerName, int newScore);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameLobbyService/GameFinished")]
        void GameFinished(string winnerName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameLobbyServiceChannel : Client.GameLobbyServiceReference.IGameLobbyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameLobbyServiceClient : System.ServiceModel.DuplexClientBase<Client.GameLobbyServiceReference.IGameLobbyService>, Client.GameLobbyServiceReference.IGameLobbyService {
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameLobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public bool JoinLobby(string token, string gameCode, bool isGuest, string guestName) {
            return base.Channel.JoinLobby(token, gameCode, isGuest, guestName);
        }
        
        public System.Threading.Tasks.Task<bool> JoinLobbyAsync(string token, string gameCode, bool isGuest, string guestName) {
            return base.Channel.JoinLobbyAsync(token, gameCode, isGuest, guestName);
        }
        
        public bool CreateLobby(string token, string gameCode) {
            return base.Channel.CreateLobby(token, gameCode);
        }
        
        public System.Threading.Tasks.Task<bool> CreateLobbyAsync(string token, string gameCode) {
            return base.Channel.CreateLobbyAsync(token, gameCode);
        }
        
        public void LeaveLobby() {
            base.Channel.LeaveLobby();
        }
        
        public System.Threading.Tasks.Task LeaveLobbyAsync() {
            return base.Channel.LeaveLobbyAsync();
        }
        
        public void SendChatMessage(string message) {
            base.Channel.SendChatMessage(message);
        }
        
        public System.Threading.Tasks.Task SendChatMessageAsync(string message) {
            return base.Channel.SendChatMessageAsync(message);
        }
        
        public void StartGame(Client.GameLobbyServiceReference.GameSettings settings) {
            base.Channel.StartGame(settings);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(Client.GameLobbyServiceReference.GameSettings settings) {
            return base.Channel.StartGameAsync(settings);
        }
        
        public void FlipCard(int cardIndex) {
            base.Channel.FlipCard(cardIndex);
        }
        
        public System.Threading.Tasks.Task FlipCardAsync(int cardIndex) {
            return base.Channel.FlipCardAsync(cardIndex);
        }
        
        public void VoteToKick(string targetUsername) {
            base.Channel.VoteToKick(targetUsername);
        }
        
        public System.Threading.Tasks.Task VoteToKickAsync(string targetUsername) {
            return base.Channel.VoteToKickAsync(targetUsername);
        }
        
        public bool SendInvitationEmail(string targetEmail, string subject, string body) {
            return base.Channel.SendInvitationEmail(targetEmail, subject, body);
        }
        
        public System.Threading.Tasks.Task<bool> SendInvitationEmailAsync(string targetEmail, string subject, string body) {
            return base.Channel.SendInvitationEmailAsync(targetEmail, subject, body);
        }
    }
}
